config/routes.rb
Rails.application.routes.draw do
  get 'code/:sifra' => 'code#page', as: 'showcode'
  get 'kod' => 'code#new'
  post 'kod' => 'code#create'
  root 'code#new'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/code_controller.rb
class CodeController < ApplicationController
  def page
  	@sifra = params[:sifra]
  	@qr = RQRCode::QRCode.new( "smsto:+387832004:#{params[:sifra]}", :size => 3, :level => :h )

  end
  def new
  end
  def create
  	redirect_to showcode_path(params[:code][:sifra])
  end
  


private
def code_params
	require.params[:code].permit(:sifra)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_helper.rb
module CodeHelper
end

app/views/code/new.html.erb
<div class="container">
<h1>Unesite kod sa kartice</h1>
<%= form_for :code, url: kod_path do |f|%>
<div class="input-group">
<%=f.text_field :sifra, class: "form-control input-lg", placeholder: "Unesite kod sa tiketa",maxlength: "6", required:true%><br>

<span class="input-group-btn">
<%=f.submit 'Go', type: "button", class:"btn btn-default btn-lg"%>
</span>
</div>
<%end%>
<div>

app/views/code/page.html.erb
<div class="container">
<h1>SMS</h1>
<p>Skenirajte QR kod</p>

<%= raw @qr.as_html%>
<br>
<%= link_to 'Generisi novi', root_path, class: 'btn btn-primary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qrcode</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>